ramp4-pcar4/storylines

- OilSandsConfig_en.ts
- schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/37)
> add english config for oil sands

- OilSandsConfig_en.ts
- schema.json
- src/components/panels/slideshow-panel.vue
- src/definitions.ts
Adds the slideshow panel component, and an optional caption below the slideshow panel if provided in the config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/45)
> add slideshow panel

- OilSandsConfig_en.ts
- StoryRampSchema.json
- src/app.vue
- src/components/story/chapter-menu.vue
- src/definitions.ts
Closes #4
Add option to scroll to top of page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/56)
> Add top hexagon to navigate to top of page

- OilSandsConfig_en.ts
- src/app.vue
- src/components/panels/introduction.vue
Closes #49 
This PR adds the introduction slide. For now the logo only supports images, but maybe in the future we'd want to support vectors as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/57)
> add intro slide

- src/app.vue
Closes #7 
This PR adds the context link to the footer using the data provided in the configuration file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/58)
> add context link

- package-lock.json
- package.json
- public/410b88da-0ed1-4749-903f-5e76c24e2e5f/410b88da-0ed1-4749-903f-5e76c24e2e5f_en.ts
- public/410b88da-0ed1-4749-903f-5e76c24e2e5f/410b88da-0ed1-4749-903f-5e76c24e2e5f_fr.ts
- src/components/panels/helpers/time-slider.vue
- src/components/panels/map-panel.vue
- src/definitions.ts
- src/style.css
#17 
Adds time slider and config options, enables the slider for the two maps in Oil Sands. Since there is no demo, take a look at the slider styling and placement after and let me know what changes make sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/135)
> Add time slider

- public/410b88da-0ed1-4749-903f-5e76c24e2e5f/410b88da-0ed1-4749-903f-5e76c24e2e5f_en.ts
- public/410b88da-0ed1-4749-903f-5e76c24e2e5f/410b88da-0ed1-4749-903f-5e76c24e2e5f_fr.ts
- public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/f6f7baf4-cccb-4521-a037-b4691b0f0d49_en.ts
- public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/f6f7baf4-cccb-4521-a037-b4691b0f0d49_fr.ts
- src/components/panels/helpers/time-slider.vue
Closes #144 
Adds ability to "play" through the years on the time-slider, button turns into pause if currently animating.
I also set slider to only show 2019 at start in configs as outlined in the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/150)
> added play button to time sliders

- tailwind.config.js
Closes #151 
Updated the tailwind typography plugin styles to use proper colours for anchor links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/152)
> fix link colours in text panels

- StoryRampSchema.json
- public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.ts
- public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_fr.ts
- src/components/panels/chart-panel.vue
- src/components/panels/helpers/chart.vue
- src/components/panels/slideshow-panel.vue
- src/definitions.ts
Closes #160, #163
Changes: 
- fix chart carousel overlap with flowing text on mobile resolutions
- make chart size configurable but will need to test/adjust this on mobile when finishing #154 
- removed "Series 1" from showing up on pie chart labels on hover
- refactored `chart.vue` to be more readable and reuse code when possible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/172)
> Fix chart resizing, labels and refactor code

- src/components/story/story.vue
Closes #114 
This PR makes it so products that have an error in their config file will display an error page when loaded. Other Storyline products will be displayed as usual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/194)
> display error message for products with bad config files

- public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
- public/00000000-0000-0000-0000-000000000000/charts/en/hybridChartConfig.json
Adds a hybrid chart demo on test page with configured highcharts json file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/218)
> Add highcharts config file for hybrid chart demo

- src/components/story/story.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/250)
> Change import back to fetch for loading config files

- src/components/panels/dynamic-panel.vue
- src/components/panels/panel.vue
- src/components/story/story.vue
- src/lang/lang.csv
Closes #247, #251 
This PR adds a back button to the top of the right dynamic panel if it is not displaying the first panel. If you click the button, it will return you to the first panel.
It also makes hyperlinks bold.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/252)
> add back button to dynamic panel; make links bold

- public/index-ca-en.html
- public/index-ca-fr.html
- public/index.html
- src/components/panels/helpers/fullscreen.vue
- src/components/panels/image-panel.vue
- src/components/panels/slideshow-panel.vue
- src/components/story/chapter-menu.vue
- src/components/story/mobile-menu.vue
- src/lang/lang.csv
Closes #253 
**Changes**:
- adds an empty alt tag to images if not provided in config file 
- adds aria labels onto buttons to resolve empty button errors 
- removes highcharts editor script file for now as it adds hidden WCAG issues
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/254)
> Fix WCAG issues for missing alt tags and empty buttons

- src/router/index.ts
To fix special French characters in hyperlinks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/257)
> Add decode to router hash links

- public/index-ca-en.html
- public/index-ca-fr.html
- public/index.html
Title
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/264)
> Comment out all highchart-editor scripts

- src/components/panels/map-panel.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/278)
> do not truncate details links

- public/index-ca-en.html
- public/index-ca-fr.html
- public/index.html
- src/components/editor/chart-editor.vue
- src/components/editor/helpers/chart-preview.vue
- src/components/panels/chart-panel.vue
- src/definitions.ts
- src/lang/lang.csv
Initial work done for #243 
**Changes**:
- able to create multiple charts and preview a chart gallery in editor 
- able to delete charts in gallery preview (altho could be refined to delete by a unique chart ID or something)
- implements UX mockups for chart panel editor 
**TODO**:
- make edit functionality work + save highcharts editor info independently for each chart
- improve on chart editor modal styling 
- save config functionality
- official French translations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/283)
> Chart gallery editor work part 1

- src/components/editor/helpers/image-preview.vue
- src/components/editor/image-editor.vue
- src/components/panels/map-panel.vue
- src/lang/lang.csv
Closes #268, #276
**Changes**:
- adds unofficial French translations and button tooltips for image editor panel
- removes `rv-trap-focus` from map component to fix hyperlink issues and keyboard trap
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/284)
> Fix link focus issues and keyboard map trap

- src/components/editor/chart-editor.vue
- src/components/editor/helpers/chart-preview.vue
- src/components/editor/helpers/image-preview.vue
- src/components/editor/image-editor.vue
- src/components/editor/slide-editor.vue
- src/components/panels/helpers/chart.vue
- src/definitions.ts
Closes #288, #290, part of #307 
**Changes**: 
- load images gallery in editor slide from existing config 
- load charts gallery in editor slide from existing config 
- opening modal highcharts editor for loaded charts is able to display previews when editing (data section seems to reset though)
> Load image and chart gallery based on existing product

- .github/workflows/build.yml
- .github/workflows/main.yml
- .github/workflows/pages-cleanup.yml
- .github/workflows/pages.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/321)
> Test demo build

- .github/workflows/build.yml
- .github/workflows/main.yml
- .github/workflows/pages-cleanup.yml
- .github/workflows/pages.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/322)
> Setup gh-pages builds for story-ramp

- src/components/panels/slideshow-panel.vue
Porting over changes from https://github.com/ramp4-pcar4/storylines-editor/pull/176
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/325)
> Add slideshow captions to individual images

- src/components/panels/image-panel.vue
- src/components/panels/slideshow-panel.vue
Related to https://github.com/ramp4-pcar4/storylines-editor/pull/194
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/328)
> Lazy Image Loading

- src/components/panels/chart-panel.vue
- src/components/panels/slideshow-panel.vue
Closes #334
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/346)
> Fix arrow and pagination placement on slideshows

- src/components/panels/dynamic-panel.vue
Closes #349
When dynamic content changes the window will scroll to the top of the right side dynamic panel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/351)
> Scroll to dynamic content on change

- src/components/panels/audio-panel.vue
- src/components/panels/chart-panel.vue
- src/components/panels/dynamic-panel.vue
- src/components/panels/helpers/chart.vue
- src/components/panels/helpers/time-slider.vue
- src/components/panels/image-panel.vue
- src/components/panels/map-panel.vue
- src/components/panels/panel.vue
- src/components/panels/slideshow-panel.vue
- src/components/panels/text-panel.vue
- src/components/panels/video-panel.vue
- src/components/story/chapter-menu.vue
- src/components/story/introduction.vue
- src/components/story/mobile-menu.vue
- src/components/story/slide.vue
- src/components/story/story-content.vue
- src/components/story/story.vue
- src/router/index.ts
- tsconfig.json
- vue.config.js
More setup for #347 
Changes import alias path to avoid overlap with editor repo imports.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/360)
> Change import alias path

- src/components/panels/chart-panel.vue
- src/components/panels/slideshow-panel.vue
- src/components/story/slide.vue
Cleaning up a few imports missed from https://github.com/ramp4-pcar4/story-ramp/pull/360
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/361)
> Update import paths missing new alias

- public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
- src/components/story/story.vue
Fixes anchor links with `target="_self"` adding the new tab icon. Added a link in the dynamic panel for testing purposes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/362)
> Fix self target anchor links adding icon

- StoryRampSchema.json
- public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
- public/00000000-0000-0000-0000-000000000000/assets/en/cpts-lg-en.html
- public/00000000-0000-0000-0000-000000000000/assets/en/video1-en.mp4.vtt
- src/components/panels/video-panel.vue
- src/definitions.ts
- src/lang/lang.csv
Closes #359 
Worked on with @JahidAhmed 
Added video functionality for basic panels as found in the demo product. Most of the options are already configurable. There are a list of remaining tasks that I wrote as a comment in `video-panel` but can also list here: 
The first two points here are definitely the highest priority.
**Testing**: 
- video controls accessibility
- working captions
- transcripts embedded below video if included in config 
- general working functionality
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/369)
> Add video panel support

- .github/workflows/build.yml
Attempt to fix build issues for https://github.com/ramp4-pcar4/story-ramp/pull/380
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/387)
> Upgrade workflow node version

- .github/workflows/build.yml
Attempt to fix build issues for #386
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/388)
> Test build node version

- package-lock.json
- package.json
- src/components/panels/dynamic-panel.vue
- src/components/panels/helpers/chart.vue
- src/components/panels/video-panel.vue
- src/components/story/chapter-menu.vue
- src/components/story/introduction.vue
- src/components/story/mobile-menu.vue
- src/components/story/story-content.vue
- storylines-plugin.ts
- vue.config.js
Connected to https://github.com/ramp4-pcar4/storylines-editor/pull/242
Adds support for Vue 3 version of the Storylines package that is being used in the editor PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/391)
> Add Vue 3 version of Storylines plugin

- public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_fr.json
- src/components/panels/helpers/chart.vue
- src/components/panels/map-panel.vue
- src/lang/lang.csv
Closes #418 
Set translation options for highcharts if the product is in FR.
Steps:
1. Load FR product - https://ramp4-pcar4.github.io/story-ramp/FR-chart-context-menu/#/fr/00000000-0000-0000-0000-000000000000
2. Navigate to any chart
3. Check labels are FR translated
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/419)
> add FR support for chart export menu options

- StoryRampSchema.json
- public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
- src/components/panels/helpers/point-of-interest-item.vue
- src/components/panels/interactive-map.vue
- src/components/panels/panel.vue
- src/components/panels/slideshow-panel.vue
- src/definitions.ts
#404 
- This PR adds support for a transitional map panel. This is a config-only implementation for now as we only need it for one project.
Steps:
1. Test the demo on different browsers and with different screen resolutions to ensure everything works as expected! Each section should take you to a different point on the map.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/420)
> add transitional map panel

- package.json
Update npm version from 3.2.4 to 3.2.6 for release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/473)
> update NPM version to 3.2.6

- public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
- public/00000000-0000-0000-0000-000000000000/assets/en/cumulative-effects.md
- src/components/panels/video-panel.vue
https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/23
- [FIX] video panel styling (centering video content and reducing width)
- added transcript file for YT video
Added a single video panel slide containing the "What are cumulative effects?" video to mimic TCEI product.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/478)
> fix YT video styling for TCEI product

- .github/requirements.txt
- .github/slack-bot.py
- .github/workflows/slack-bot.yml
- Adds a Slack bot that posts every time a new PR is created in the story-ramp repo, giving details of the PR as well as an AI-generated summary of its description.
- The AI summary uses the [Pegasus summarizer](https://huggingface.co/tuner007/pegasus_summarizer) model, which seems to do a good job and requires significantly fewer compute resources than a generalist model (ala LLAMA 3.2).
- The Python `transformers` library is used to handle the model.
Links to the PR types list pages ("PR: Active", "PR: Geo", etc.) are hard-coded, and will need to be manually changed if the names of the types are modified.
QA Testing
Please test against main branch https://ramp4-pcar4.github.io/ramp4-pcar4/main/demos/enhanced-samples.html
1. Read the YAML file, and ensure the workflow is correct.
2. Once …
> Add Slackbot

- src/components/story/introduction.vue
- src/lang/lang.csv
https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/178
- Adds a French translation to the 'scroll to story' button in the introduction slide.
Steps:
1. Open the demo link.
2. Hover over the "scroll to story" button and ensure it's displaying in English.
3. Change the language to French.
4. Hover over the button again and ensure it's displaying in French.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/538)
> add French translation to 'scroll to story' button

- package.json
Updated the version to include changes from https://github.com/ramp4-pcar4/story-ramp/pull/546
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/548)
> Update version again

- StoryRampSchema.json
- public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
- src/components/panels/helpers/point-of-interest-item.vue
- src/components/story/background-image.vue
- src/components/story/story-content.vue
- src/definitions.ts
- src/lang/lang.csv
Closes https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/234, part of https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/235
- [FEATURE] make long POI text expandable on mobile past a specific threshold
- [FEATURE] add configurable alt text to bg images
- check that alt text exists on dynamic slide background image
- in mobile view, view the interactive map with the truncated text content for long sections
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/549)
> Make poi text on mobile expandable + bg alt text

- StorylinesSchema.json
- package.json
- vite.config.ts
#506
- Add `version` property to schema and set it to `1.0.0`
- Add schema file to dist folder upon building 
- Editor changes have been made in:  https://github.com/ramp4-pcar4/storylines-editor/pull/574
Steps:
1. Open a product
2. Ensure there are no errors
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/550)
> Add version to storylines schema

- public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
- src/components/panels/helpers/toc-item.vue
- src/components/story/chapter-menu.vue
- src/components/story/horizontal-menu.vue
- src/components/story/mobile-menu.vue
- [FIX] fix default ToC not properly hiding ToC items with `includeInToc` set to false
Check the ToC and should be behaving appropriately. Demo link: https://ramp4-pcar4.github.io/storylines/fix-default-toc/#/en/00000000-0000-0000-0000-000000000000
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/storylines/557)
> Fix default toc not hiding config menu items

- StorylinesSchema.json
- package.json
Issue [#731](https://github.com/ramp4-pcar4/storylines-editor/issues/731) & PR [#735](https://github.com/ramp4-pcar4/storylines-editor/pull/735)
- Fixes issue where advanced editor schema validation was not working for dynamic panels
- published version 3.5.8 to NPM
* Test PR [#735](https://github.com/ramp4-pcar4/storylines-editor/pull/735) and ensure schema validation works for dynamic panels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/storylines/601)
> Update schema for dynamic panel items
