ramp4-pcar4/storylines

src/app.vue
src/components/panel.vue
src/components/slide.vue
src/components/text-panel.vue

Basic implementation for slides and panels.
Given a config, the slide component will display either one or two panels. If one panel is provided, it will take up the whole slide. If two are provided, the panels will be displayed next to each other.
The panel component acts as a base class for the individual panel types. Because we don't currently have any of the panel types created, most of these are `undefined` for now. I've created a very simple text component for demo purposes only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/38)

create basic slide and panel components

---

OilSandsConfig_en.ts
src/app.vue
src/components/panels/audio-panel.vue
src/components/panels/chart-panel.vue
src/components/panels/image-panel.vue
src/components/panels/map-panel.vue
src/components/panels/panel.vue
src/components/panels/slideshow-panel.vue
src/components/panels/video-panel.vue
src/components/slide.vue
src/definitions.ts

Creates temporary components for all of the unimplemented panel types, and slides should appear from the actual config file now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/41)

make slides use actual config; create temporary components

---

src/app.vue
src/components/panels/panel.vue

Closes #5 and #6 
This PR removes the Sharepoint and Github links from the header bar, and adds in a small link to the StoryRAMP repo at the bottom. I also removed a console.log statement that I forgot to remove when working on the panel PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/48)

remove header links, add link to github repo

---

src/components/slide.vue

Closes #30 
Adds anchor points for each slide based on the order they appear in the config file. For now, the anchor point is simply an ID, but if we want it to be fancier (i.e., using one of the headers in the slide for example), we can have a discussion on this during a planning meeting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/50)

add slide anchors

---

OilSandsConfig_en.ts
schema.json
src/app.vue
src/components/story/chapter-menu.vue
src/components/story/slide.vue
src/components/story/story.vue
src/definitions.ts

Closes #47 
Reorganizes some Vue component files and connect paginator to using the new slides/panels. Adds a title property to slides in the config/schema that was discussed. The old story map has also been removed with this PR but the files remain (unused).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/53)

Connect paginator to new slides/panels layout

---

src/components/story/story.vue

Closes #54 
Hexagons on paginator now fill properly based on what slide is in focus and heading text is bolded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/59)

Fix paginator focus issues

---

src/components/panels/text-panel.vue

Closes #62
Adds target blank attribute to all Markdown `href` links in StoryRamp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/69)

open all markdown links in new tab

---

public/index-ca-en.html
src/app.vue
src/components/story/chapter-menu.vue
vue.config.js

Closes #12 and #13 
This PR adds StoryRAMP to the Canada.ca template and fixes a bunch of styling. The breadcrumb should also match other ECCC links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/74)

integrate Canada.ca template and add breadcrumb

---

src/components/panels/slideshow-panel.vue
src/components/panels/text-panel.vue

Closes #78 
This PR adds HTML support to text slides. Now, both markdown and HTML text will be displayed as intended.
I've also added this same functionality to captions (which only currently exist for the slideshow panel).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/84)

support for HTML text in config file + markdown support for captions

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.ts
src/components/panels/chart-panel.vue
src/definitions.ts

Closes #85 
Adds some highchart configurable options to the StoryRAMP configuration file, which are used for charts that have a CSV input.  The ones I've included for now are `title`, `subtitle`, `xAxis` and `yAxis` labels, `type`, and `credits`. We can add more as needed later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/92)

add highchart config options to the StoryRAMP config file

---

package.json
src/app.vue
src/components/panels/chart-panel.vue
src/components/story/story-ramp.vue
src/main.ts
src/router/componentHooks.ts
src/router/index.ts

Closes #75 
Now accepts `uid` and `lang` parameters in the form of `/[lang]/[uid]` to load the specified config. Added `vue-router` and created three routes: one as the home page that loads in the default test page (no params passed), one that accepts only the `uid` (`/[uid]` ) and defaults to `en` for the language, and one with both params. It is able to perform dynamic route matching, but I'm not sure if that is needed here.  
If an invalid set of params are passed, the page redirects to the canada.ca 404 [page](https://www.canada.ca/errors/404.html).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/94)

Load config files based on URL passed UID and lang params

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.ts
src/components/panels/dynamic-panel.vue
src/components/panels/panel.vue
src/definitions.ts

Closes #77 
This PR adds a new panel type: the `dynamic` panel, a single panel component that acts as a double panel. On the left side it displays text, and on the right side it displays some other type of panel. This right panel can be changed dynamically by clicking on links on the text panel.
In the StoryRAMP configuration file, a dynamic panel requires two properties: the `text` property, which is what will be displayed on the left side. This can contain markdown and HTML like a regular text panel. The dynamic panel also requires a `children` property. This is an array that contains the configs for the panels that may be displayed on the right side. You must specify an ID for these panels.
The most difficult part of this issue for me was trying to figure out a good way to add the …

Add dynamic panel to allow panel switching

---

src/components/panels/chart-panel.vue
src/components/panels/panel.vue
src/components/story/story-ramp.vue
src/definitions.ts
src/shims-vue.d.ts
src/types.d.ts

Fixes most of the `any` typing instances and exposes `$papa` and `$route` to be identified on `Vue` instances. Also removed some of the unused properties in `chart-panel`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/96)

TS typing/error fixes

---

src/router/index.ts

Closes #98
Vue router now checks if any hash anchor tag is attached to the URL and scrolls to that slide. For instance, http://localhost:8080/#/en/00000000-0000-0000-0000-000000000000#oil-sands-deposits should now work properly. Added a new issue #100 for adding the HTML5 history mode as suggested by @spencerwahl in an earlier review as it would seem helpful to eventually eliminate the # in the middle of URLs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/101)

Add ability to scroll to anchor tags vue router

---

src/components/panels/slideshow-panel.vue

Closes #105 
The `altText` property was not being added to images correctly in the slideshow panel. There was a small inconsistency in the property name for slideshow images which this PR fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/110)

fix altText property on slideshow panel

---

src/components/story/chapter-menu.vue
src/components/story/story.vue

Closes #102, #106
Fixes for the following paginator accessibility issues: 
- top hexagon tooltip not showing on keyboard nav or requiring additional tab to display tooltip
- added idx to anchors in the case of identical href names 
- title text cutoff at bottom 
- made side navigator for slide content scrollable while title stays fixed in the case of too many slides which gets cut-off (not sure if there is a better solution for this is but this seems to solve all of the cases outlined in original issue including keyboard navigation)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/116)

Paginator accessibility fixes

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.ts
src/components/panels/image-panel.vue
src/definitions.ts

Closes #121 
This PR adds a `config` property to the config for image panels. The caption appears below the image and supports both HTML and markdown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/122)

add caption property to image slide

---

package.json
src/components/story/story-ramp.vue

Closes #108 
Displays a spinner while the config file is being fetched in order to prevent the default text from being displayed briefly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/124)

add loading spinner while config is fetched

---

src/components/panels/chart-panel.vue
src/definitions.ts

Closes #117
Rewrites parsing functionality in `chart-panel` to add support for pie charts. All the pie charts from the Ethlyene Glycol and Pulp and Paper configs should display properly. It is displayed as follows: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/128)

Add support for basic pie charts

---

src/components/panels/chart-panel.vue
src/definitions.ts

Closes #126 
Enables the highcharts hamburger menu with all the required options through importing two additional highcharts modules. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/129)

Add chart context menu options

---

StoryRampSchema.json
src/components/panels/chart-panel.vue
src/components/story/story-ramp.vue
src/definitions.ts

Closes #107 
Sets lang property of page every time a new config is loaded so the lang in RAMP will match the config language. Also added a toggle config option for highcharts hamburger menu that I missed in #126.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/131)

Set page language based on lang of config

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.ts
src/components/panels/chart-panel.vue
src/components/panels/panel.vue
src/definitions.ts

Closes #103 
Adds config option for specifying an array of colours to be used in charts. These correspond to the order of columns given in the CSV data. Also adds back the behavior of text panels scrolling while graphic panels are sticky.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/136)

Make chart colours configurable

---

src/components/panels/image-panel.vue

Closes #127 
This PR ensures that images don't appear larger than the screen height, and forces images to keep their aspect ratio so they don't appear blurry if resized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/137)

keep image aspect ratio, prevent from breaking layout

---

public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.ts
public/410b88da-0ed1-4749-903f-5e76c24e2e5f/410b88da-0ed1-4749-903f-5e76c24e2e5f_en.ts
public/410b88da-0ed1-4749-903f-5e76c24e2e5f/410b88da-0ed1-4749-903f-5e76c24e2e5f_fr.ts
public/ea24000c-7dc3-49a9-baac-c55d28dcaeb9/ea24000c-7dc3-49a9-baac-c55d28dcaeb9_en.ts
public/ea24000c-7dc3-49a9-baac-c55d28dcaeb9/ea24000c-7dc3-49a9-baac-c55d28dcaeb9_fr.ts
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/f6f7baf4-cccb-4521-a037-b4691b0f0d49_en.ts
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/f6f7baf4-cccb-4521-a037-b4691b0f0d49_fr.ts
src/components/panels/chart-panel.vue
src/components/panels/helpers/chart.vue
src/components/panels/slideshow-panel.vue
src/definitions.ts

#139 
Adds ability to have multiple charts in a chart panel.
Chart panel config changed to:
```
{
type: 'chart'
charts': [{
src: 'source1',
options: { ... }
},
{
src: 'source2'.
options: { ... }
}]
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/146)

allow multiple charts in chart panel

---

src/components/panels/helpers/time-slider.vue
src/components/panels/map-panel.vue
src/style.css

Closes #143 
Moved time slider panel out from behind legend at the same height as the mapnav buttons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/149)

adjust time slider placement, add shadow to panel

---

src/components/story/story-content.vue

Closes #138 
On initial app load, added a manual scroll to element if there is a hash attached to the end of the URL in `mounted`. Adding a small delay could also work but would delay navigation through the side menu. The hash needed to be decoded in the case of special French characters being used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/157)

Add navigation for direct links through URL on initial load

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.ts
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_fr.ts
src/components/story/story.vue
src/definitions.ts

Closes #158 
Closes #159 
When the config file is loaded, the page header will be updated to `<product title> - Canada.ca` in order to better match how the rest of Canada.ca works.
This PR also adds the dateModified property to the schema. If it is set, then the provided date will be displayed at the bottom of the Storyline product.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/166)

update page title and add date modified

---

StoryRampSchema.json
package.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.ts
src/components/panels/helpers/chart.vue
src/components/panels/helpers/fullscreen.vue
src/components/panels/image-panel.vue
src/components/panels/slideshow-panel.vue
src/definitions.ts
src/main.ts
src/shims-vue.d.ts

Closes #153 
Adds a full screen expandable option for all graphic panels. For image and slideshow panels, a toggle button is added while for chart panels, a full screen option was added to the hamburger context menu. The option is also configurable and defaults to true (enabled).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/168)

Add expandable option to graphics

---

src/components/panels/helpers/scrollguard.vue
src/components/panels/map-panel.vue

Closes #161 
The scroll guard wasn't working using the Firefox browser. It seems like the `stopPropagation()` method acts differently in Firefox than it does for other browsers, and after spending a ton of time trying things to get it to work I eventually just gave up and wrote a new implementation for the scroll guard using a RAMP3 custom panel.
An issue still exists in Firefox where the map will sometimes scroll once as the scroll guard pops up, again due to `stopPropagation` not working. I'm not exactly sure how to fix this, and if anyone else has an idea let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/171)

re-implement scrollguard to work with Firefox

---

public/index-ca-en.html
public/index-ca-fr.html

Closes #175 
Adds some extra checks to the language switch logic:
- if the URL ends in a '/', language switch will still work
- if the URL ends in a '/' and contains an anchor after it (i.e., `/<id>/#anchor`), the anchor will be removed when switching languages.
- if the URL does not end in a '/' and still contains an anchor (i.e., `/<id>#anchor`), the anchor will be removed when switching languages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/176)

add extra checks to language switch

---

public/410b88da-0ed1-4749-903f-5e76c24e2e5f/ramp-config/en/OilSandsFacilityLocations2019.json
public/410b88da-0ed1-4749-903f-5e76c24e2e5f/ramp-config/en/ReleasesandDisposalsbyMiningFacilitiesin2019(satellite).json
public/410b88da-0ed1-4749-903f-5e76c24e2e5f/ramp-config/en/ReleasestoAirbyInSituFacilitiesforAllSubstances2010to2019(timeslider).json
public/410b88da-0ed1-4749-903f-5e76c24e2e5f/ramp-config/en/ReleasestoAirbyInSituFacilitiesforAllSubstancesin2019.json
public/410b88da-0ed1-4749-903f-5e76c24e2e5f/ramp-config/fr/OilSandsFacilityLocations2019.json
public/410b88da-0ed1-4749-903f-5e76c24e2e5f/ramp-config/fr/ReleasesandDisposalsbyMiningFacilitiesin2019(satellite).json
public/410b88da-0ed1-4749-903f-5e76c24e2e5f/ramp-config/fr/ReleasestoAirbyInSituFacilitiesforAllSubstances2010to2019(timeslider).json
public/410b88da-0ed1-4749-903f-5e76c24e2e5f/ramp-config/fr/ReleasestoAirbyInSituFacilitiesforAllSubstancesin2019.json
public/ea24000c-7dc3-49a9-baac-c55d28dcaeb9/ramp-config/en/total_quantities2019.json
public/ea24000c-7dc3-49a9-baac-c55d28dcaeb9/ramp-config/en/total_releases2019.json
public/ea24000c-7dc3-49a9-baac-c55d28dcaeb9/ramp-config/fr/total_quantities2019.json
public/ea24000c-7dc3-49a9-baac-c55d28dcaeb9/ramp-config/fr/total_releases2019.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/en/phosphorus_and_nitrates_of_pnp_2010-2019.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/en/pollution_prevention_activities.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/en/total_criteria_air_contaminants_of_pnp_2010-2019.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/en/total_disposals_and_transfers_of_pnp_2010-2019.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/en/total_reduced_sulphur_of_pnp_2010-2019.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/en/total_releases_and_disposals_of_pnp_2010-2019.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/fr/phosphorus_and_nitrates_of_pnp_2010-2019.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/fr/pollution_prevention_activities.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/fr/total_criteria_air_contaminants_of_pnp_2010-2019.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/fr/total_disposals_and_transfers_of_pnp_2010-2019.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/fr/total_reduced_sulphur_of_pnp_2010-2019.json
public/f6f7baf4-cccb-4521-a037-b4691b0f0d49/ramp-config/fr/total_releases_and_disposals_of_pnp_2010-2019.json

Closes #145 
In this PR, I've modified the starting extents for each of the RAMP3 configs that default to having the legend open so that as little data as possible is covered by the legend on small resolutions.
None of the map extents should have changed significantly. I tried my best to make sure the modifications were all *just* enough so that most of the points could appear without being blocked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/177)

fix starting extents for existing projects

---

src/components/panels/chart-panel.vue
src/components/panels/dynamic-panel.vue
src/components/panels/helpers/chart.vue
src/components/panels/slideshow-panel.vue
src/definitions.ts

Closes #154 
Closes #99 
Modifies styling for dynamic panels to display properly on mobile resolutions. Made adjustments to make dqv charts responsive to resizing screen. Charts and chart carousels should no longer be cut-off on mobile screens nor overflow its parent container. 
A minor issue is that some of the longer labels will be cut-off. My thought for this is to consider removing some of the less essential labels altogether on mobile (e.g. y-axis titles, subtitles for bar/line charts, section labels for pie charts) as a way to conserve space to display the data, but we can wait and see what results from the mobile testing #29.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Make charts fully responsive and fix dynamic panels on mobile

---

src/components/panels/image-panel.vue
src/components/panels/panel.vue
src/components/panels/slideshow-panel.vue

Closes #180 
This PR fixes an issue where text would overlap with captions for images and slideshows. It also fixes another Firefox-exclusive issue where markdown text would appear on top of images, maps and charts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/184)

fix text overlapping maps and images

---

src/components/panels/helpers/time-slider.vue
src/components/panels/map-panel.vue

Closes #178
- Removed some margins and shrunk the height of the panel
- Hid every other label as they would overlap eachother
- Made the time slider take available width
- Moved play button out of the way of the slider handles
Non-mobile styles left alone
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/191)

Fix time slider display on mobile

---

src/components/panels/map-panel.vue

Closes #185 
On mobile, maps with a title section will no longer cut off the text below.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/193)

fix map titles cutting off text on mobile

---

src/components/story/story.vue

Left the no param root route but page will now default to display the error page when loaded with no URL params. Can also use the 404 canada.ca page if that is the preferred option. Removed the test page from being the default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/199)

Replace default test page at root route with error page

---

src/components/panels/map-panel.vue

Changes in this PR:
- whitespace is no longer visible above maps with no title
- maps in the `Ethylene Glycol` product will no longer think that the legend panel is offscreen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/201)

fix legend offscreen bug; remove whitespace above maps with no title

---

public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
public/00000000-0000-0000-0000-000000000000/charts/en/csvUrlChart.json
src/components/panels/helpers/chart.vue
src/definitions.ts

Closes #217 
Fixes timing issue of not properly fetching external CSV url when loading in custom config for highcharts. Added a sample from https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/data/livedata-csv to demo page to show CSV getting properly read.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/219)

Fix external CSV url config not loading chart

---

src/components/panels/helpers/time-slider.vue
src/components/panels/map-panel.vue

Closes #200 
Timeslider is now minimizable to one line. I tried to make it minimize by default on mobile but it started breaking things and I couldn't figure out how to unbreak it.
Also I will be opening an issue to set up a translation file and add tooltips for the play and minimize buttons on the timeslider.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/221)

add minimize control to timeslider

---

package.json
src/components/editor/editor.vue
src/lang/lang.csv
src/main.ts
src/shims-vue.d.ts

Closes #229 and #230
- added a markdown editor to the editor page
- added a "generate config" button which, at the moment, generates an example config which is filled from the fields on the page and prints it to the console
- added a "View English/French Config" button to the top right of the page which switches between the English and French configuration files. This button doesn't switch the language of the page, only the configuration file.
These features have been added to the basic editor page for now. We can move them around and change how they look as we develop further.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/238)

add demo markdown editor; swap to French config

---

src/components/editor/editor.vue

Fixes an issue where all buttons in the main Storylines app had a black border around them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/240)

remove unintended border from main storylines app buttons

---

src/components/panels/dynamic-panel.vue
src/components/panels/loading-panel.vue
src/components/panels/panel.vue
src/definitions.ts

Closes #246 
This PR fixes an issue where dynamic panels wouldn't load multiple maps in the same panel. A quick loading spinner is now shown when switching between panels so maps will load properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/248)

fix maps not loading in dynamic panels

---

public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/helpers/chart.vue

Closes #245, #244
**Changes**: 
- make charts take up full available width space on normal resolutions, height remains untouched
- fix mobile flexbox space overlap between charts and text content
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/249)

Adjust chart space and reflow

---

src/components/panels/dynamic-panel.vue

Closes #255 
The back button is now displayed in the top-right corner of the left panel, and follows scrolling until the section ends. On mobile, the button is displayed below the second panel.
A demo of this implementation can be found [here](https://github.com/ramp4-pcar4/story-ramp/issues/255#issuecomment-1303809955)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/256)

dynamic panel back button no longer covers panel

---

StoryRampSchema.json
src/components/panels/text-panel.vue

#260 
Adds a config option that can be used to have a panel title be something other than `h2`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/261)

Add config option for changing title tag

---

src/components/panels/map-panel.vue

I decided to go the easy route and just add a more specific selector that unsets `max-width`.
I remember for ramp4 that trying to get tailwind preflight to behave is a mess and images in some places are styled with the `max-width: 100%` in mind.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/262)

fix broken basemap thumbnails

---

src/components/panels/dynamic-panel.vue

Closes #270 
Adds a `href` attribute to the dynamic panel links in order to make them focusable. Since these are now treated as proper anchor tags, they appear bold and blue like other links. In order to distinguish between these dynamic anchor tags and regular anchor tags, the underline below will be dotted instead of a solid line.
Example:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/274)

make dynamic links focusable

---

src/components/panels/dynamic-panel.vue
src/components/story/chapter-menu.vue

Closes #275 
Added a buffer to the bottom of the chapter menu so that things should not get cut off on mobile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/277)

fix cut off chapter menu

---

src/components/editor/chart-editor.vue
src/components/editor/editor.vue
src/components/editor/helpers/image-preview.vue
src/components/editor/image-editor.vue
src/components/panels/slideshow-panel.vue
src/definitions.ts

Closes #234 
**Changes**:
- implements image gallery slide editor/creator based on UX mockups (see image below) 
- option to upload or drag and drop images
**Missing**:
- ability to reorder images in preview mode
- file/config saving mechanism dependent on #227
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/259)

Add image/gallery panel editor

---

src/components/panels/helpers/fullscreen.vue

Closes #266 
This PR ensures fullscreening on mobile devices acts the same as fullscreening on desktop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/280)

fix fullscreen styling on mobile

---

src/components/panels/dynamic-panel.vue
src/components/panels/map-panel.vue

Fixes console errors for `setAttribute` error caused by conditional rendering and missing `i18n` for scrollguard component.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/281)

Fix console errors for set attribute and missing i18n

---

src/components/panels/helpers/fullscreen.vue
src/lang/lang.csv

Closes #269 
Makes the full screen button a bit more visible when placed over a dark image, and adds a tooltip to the button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/282)

make fullscreen button more visible, add tooltip

---

src/components/editor/chart-editor.vue
src/components/editor/editor.vue
src/components/editor/image-editor.vue
src/components/editor/slide-editor.vue
src/components/editor/slide-toc.vue
src/components/editor/text-editor.vue

#233 #237 
Slide table of contents where you can add, remove and reorder slides.
Slides can be given a title and both left and right panels are editable. Left panel is constrained to text only, right panel has a dropdown for panel type. Text panels are synced with the config, I had no idea how to sync the image panel properly (it is given the panel as a prop though so all that needs to be done is setting it).
Added a basic UI for things vaguely following the mockups, will need more work done but things are there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/285)

editor: add new/remove slide functionality and toc

---

src/components/editor/chart-editor.vue
src/components/editor/helpers/chart-preview.vue
src/components/editor/helpers/image-preview.vue

Closes #242, #243
*NOTE*: The main add chart button summoner automatically saves the last added chart options by default when adding multiple charts, not sure if this is a critical bug but if so can log a new issue for that. 
**Changes**: 
- adds edit functionality to each individual chart in gallery preview
- fixes highcharts editor modal styling so that header buttons are not cut-off, chart dimensions are on same line, etc. 
- enforces a no-duplicate chart name rule so that each edit button has its own unique ID to summon its corresponding chart modal (throws a screen alert for error), but can also adapt to a unique ID for each chart as a possible enhancement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Add edit functionality to chart editor and fix modal styling 

---

package.json
src/components/editor/chart-editor.vue
src/components/editor/editor.vue
src/components/editor/image-editor.vue
src/components/editor/slide-editor.vue
src/components/editor/text-editor.vue

This PR adds functionality to the save button. Clicking the button generates a ZIP file with the following Storylines project structure:
- {UUID}
- assets
- en
- fr
- charts
- en
- fr
- ramp-config
- en
- fr
This is what is currently saved:
- the Storylines configuration file (at the moment, **only the language being worked on**. We still need to make it so we can swap between English and French configs)
- Uploaded images (**not saved to Storylines config yet**, but images are added to ZIP)
- Created charts (**not saved to Storylines config yet**, but json files are added to ZIP)
At the moment, clicking the button downloads the ZIP file to your browser for testing purposes. The code is there to upload the ZIP file to a server via Axios. The server code is already written ([see demo …

generate saved product ZIP; save images and charts to ZIP

---

src/components/panels/map-panel.vue

Closes https://github.com/ramp4-pcar4/story-ramp/issues/319 (PR 1/2, other PR is in the editor repo)
This PR fixes an issue where maps with a title will have their bottoms cut off. Maps with a title will now be slightly less tall in order to fit on the screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/326)

fix bottom of map being cut off when a title is present

---

src/components/panels/helpers/time-slider.vue
src/definitions.ts

Closes #329 
Time slider now loops through layers to change filter sql.
Added a config param to give an array of layer IDs for the time slider to affect, not supplying this param will have it affect every layer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/330)

Time slider now affects multiple layers

---

src/components/panels/map-panel.vue

Closes #339 
Fixes an issue where maps with a title would take up the entire screen height on mobile view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/342)

fix map height on mobile resolution

---

src/components/story/introduction.vue

Closes #207 (2/2)
Fixes issue where the intro slide wasn't appearing if the logo section was missing from the config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/343)

fix intro slide not loading when logo is missing

---

src/components/story/story.vue

Closes #340 
This PR fixes an issue where long names just extend the width of the screen. Ellipses are now added to the end of the title. I did attempt to see how it would work to have the title wrap to the next line, but it causes a ton of issues with how we have the second slide stick to the top on mobile view.
As far as the chart problem goes, I'm unable to test the exact product that the issue was found on, but other charts seem to work well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/348)

fix long names adding a horizontal scrollbar to app

---

src/components/panels/helpers/chart.vue
src/definitions.ts

Closes #337 
This PR removes the 'View Data Table' option from Highcharts in the app. I opted to remove them because I don't think they have a purpose for our app, and because Highcharts doesn't allow for much flexibility with these tables to make them work properly on mobile. This option was already unavailable for charts sourced from CSV files, so it makes sense to have some consistency with JSON files as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/354)

remove view data table option from highcharts

---

src/components/panels/dynamic-panel.vue

Closes #352 
This PR fixes the positioning of the back button on mobile view. It required a slight re-structuring of the dynamic panel, but the back button should behave as normal in regular view, and should now follow the screen as you scroll on mobile view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/355)

fix back button positioning on mobile

---

public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
public/00000000-0000-0000-0000-000000000000/charts/en/1 Mount royal.csv
public/00000000-0000-0000-0000-000000000000/charts/en/EG_releases_2019_en.csv
public/00000000-0000-0000-0000-000000000000/charts/en/Total releases of ethylene glycol for 2019, by province_en.csv
src/components/panels/helpers/chart.vue
src/components/panels/helpers/time-slider/time-slider.vue
src/main.ts

Fixes access to Vue Papa Parse library in composition API by using provide/inject. Added a few CSV sourced charts for testing on the demo page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/393)

Fix CSV sourced charts in Vue 3

---

src/components/panels/helpers/time-slider/time-slider.vue
src/components/panels/map-panel.vue

Fixes placement of timeslider buttons and legend checkboxes in RAMP maps
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/394)

small RAMP style fixes

---

src/components/story/chapter-menu.vue

For #395 
**Changes**
- CSS changes to ensure `chapters.title` hides behind ToC correctly, it was showing a bit before
**Notes**
Before changes:
After changes:
**Testing**
1. Close the expanded Table of Contents. 
2. Ensure that there is no text peeking out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/397)

Text hidden behind ToC

---

README.md
package.json

Closes #368 
Provided documentation for usage as Vue plugin. Not yet published to NPM, but once everything is functional and approved for Marketing site and editor repos we can create a proper 1.0.0 release with these docs included.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/380)

Add documentation for plugin usage in NPM

---

src/components/story/introduction.vue
vue.config.js

Related https://github.com/ramp4-pcar4/storylines-editor/issues/245
This PR fixes an issue where the logo isn't appearing when you enter preview mode in the Storylines editor. Because it is not guaranteed that images are uploaded to the server when in preview mode, we use `URL.createObjectURL()` to create a temporarily accessible path to the image. It seems like the temporary image source was being overwritten somehow (possibly due to the forceUpdate?) when opening the preview which is why the image was not appearing.
The issue should now be fixed, but since this PR is in the main repo and not the editor we won't be able to test it through the demo link.
Note: the code added to `vue.config.js` in this PR just fixes an issue with building locally.
- - -
This change is [<img …

fix logo not displaying when configFileStructure is provided

---

src/components/story/story-content.vue

Related to #374 
It seems like the problem was being caused by the smooth scrolling behavior. Removing this (plus adding a very short timeout to allow for content to load) fixes the issue. Smooth scrolling should still be working when clicking on items in the table of contents.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/408)

fix anchor links

---

README.md
package.json

Renames NPM package name and published here: https://www.npmjs.com/package/ramp-storylines_demo-scenarios-pcar 
There was no dedicated method for NPM renaming, so had to deprecate the old package as a workaround: 
https://www.npmjs.com/package/ramp-storylines
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/414)

Rename and publish NPM package

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/chart-panel.vue
src/components/panels/helpers/chart.vue
src/components/panels/image-panel.vue
src/components/panels/slideshow-panel.vue
src/definitions.ts

#410 and #353 
- The slideshow panel now supports all panel types instead of just images.
- The charts panel no longer contains a carousel. Chart galleries should be replaced with a slideshow (see breaking changes section below).
- Text panels in the slideshow will display a scrollbar if they are too long.
- As per [Aleks' feedback here](https://github.com/ramp4-pcar4/story-ramp/pull/353#issuecomment-1689980297), I have removed the ability to switch between slides by dragging the mouse in order to allow the user to pan the map and to copy text if they'd like.
- As discussed [here](https://github.com/ramp4-pcar4/story-ramp/pull/353#pullrequestreview-1446501797), I have removed the carousel from the chart panel. To fix existing chart galleries, change the `type` from `chart` to `slideshow`, …

add support for dynamic slideshow

---

src/components/panels/dynamic-panel.vue
src/components/panels/panel.vue
src/components/story/slide.vue

https://github.com/ramp4-pcar4/storylines-editor/issues/252, https://github.com/ramp4-pcar4/storylines-editor/pull/274
- Previously, we would always put the text panel on the left and sticky the right panel if it was multimedia. Logic has now been modified to respect config ordering.
- On mobile, the multimedia panel will be prioritized first over a text panel. For all of the ordering rules see the comment in the PR.
Steps:
1. Open the demo page and ensure that the `Default RAMP4 Sample` slide is swapped correctly. The map should be on the left and the text should be on the right. In mobile view, the map should be stuck to the top.
2. The `Pollution in your neighbourhood` slide has two text panels next to each other. Ensure that these are still displaying in the correct order.
3. Play …

rework panel ordering to allow multimedia on the left panel

---

package.json
src/components/story/horizontal-menu.vue
src/components/story/introduction.vue
src/components/story/story-content.vue
src/components/story/story.vue
src/definitions.ts

#402 
- Added horizontal table of contents component
- Implementation is such that the config of the project metadata will determine if the table of contents will be horizontal or vertical
- Updated version to `3.1.2` in `package.json`
With this PR, the horizontal table of contents will be shown in the demo (the vertical table of contents has been commented out along with some styles, will be removed before merging) to test the component.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413)

Horizontal table of contents implementation

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/dynamic-panel.vue
src/components/panels/image-panel.vue
src/components/panels/map-panel.vue
src/components/panels/panel.vue
src/components/panels/slideshow-panel.vue
src/components/panels/text-panel.vue
src/components/story/background-image.vue
src/components/story/slide.vue
src/components/story/story-content.vue
src/definitions.ts

#401 
- Adds support for transitional background images. The configuration flag is `backgroundImage` and takes a path to an image. 
- When a background is active, text components (text slides, captions, titles, etc.) will be placed in a semi-transparent container to keep an accessible contrast.
Steps:
1. Open the sample page and scroll down.
2. Ensure that contrast is OK for text, captions, titles, etc.
3. Ensure that everything is working well on mobile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/417)

add support for transitional background images

---

package.json
src/components/panels/helpers/chart.vue
src/components/panels/map-panel.vue

There was no issue posted, but maps were not displaying in the editor preview.
- If the `configFileStructure` prop is provided, the panel will grab the map config from the ZIP file instead of attempting to fetch it. 
- If the prop is not provided, it will be fetched as usual.
- Also fixes a bug with charts in the editor.
Steps:
1. Open the sample link and ensure that everything still works as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/430)

fix map configuration loading logic

---

src/components/story/story-content.vue

#427 
- This PR fixes the ToC bubbles not highlighting when scrolling through a product. It also should fix the issue we were having with having an unnecessary horizontal scrollbar. 
Steps:
1. Open the demo.
2. Scroll through the app and ensure the bubbles on the left are being highlighted correctly.
3. Click on a bubble and ensure the page doesn't jump to the right.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/436)

fix broken ToC highlight

---

src/components/story/chapter-menu.vue
src/components/story/mobile-menu.vue

#371, #421
- This PR changes the "Scroll to Top" button to be more distinct from the other chapter hexagons in the navigation bar.
- This PR also updates the positioning of tooltips so as not to cover the hexagons/chapter titles.
The new scroll to top button. Let me know if I should make any modifications!
Steps:
2. Ensure that the new icon is appearing correctly.
3. Ensure that tooltips are appearing properly and no longer cover the hexagon or chapter title.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/437)

update 'scroll to top' svg; fix tooltip placement

---

package.json
src/components/panels/dynamic-panel.vue
src/components/panels/image-panel.vue

#432 
- This PR fixes an issue where images were not appearing correctly in preview mode.
This is intended to fix an issue in the editor preview, so it won't be noticeable on the Storylines demo page. Just ensure that existing images are appearing as they were before.
Steps once we update the npm package in the editor repo:
2. Load a project and create a new image panel. Add an image and click the 'Preview' button in the top right.
3. Ensure that the image is displaying correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/439)

fix images not displaying in preview mode

---

src/components/panels/helpers/time-slider/time-slider.vue
src/components/story/background-image.vue

#441 
- Fixes some accessibility issues with the time slider.
- Also fixes an accessibility issue with the new transitional backgrounds.
Steps:
1. Open the sample page.
2. Scroll down to a map with a time slider (the slide titled `Trends in mine tailings reported from surface mining facilities` has one)
3. Open the WAVE toolbar and ensure there are no empty button or contrast issues with the time slider.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/442)

fix WCAG errors

---

src/components/panels/slideshow-panel.vue

https://github.com/ramp4-pcar4/storylines-editor/issues/335
- Removes unnecessary whitespace below charts in slideshow panels.
Steps:
2. Jump to the section titled `Chart Gallery` in the table of contents.
3. Ensure that there is no whitespace below the charts.
4. Ensure other slideshows are still displaying correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/448)

remove large amount of whitespace below charts in slideshow panel

---

src/components/story/horizontal-menu.vue
src/lang/lang.csv

https://github.com/ramp4-pcar4/storylines-editor/issues/346, https://github.com/ramp4-pcar4/storylines-editor/issues/337, https://github.com/ramp4-pcar4/storylines-editor/issues/328
- The `Return to top` button will now be vertically aligned.
- Removed an unnecessary left margin from the active chapter button to ensure the text is centered in the button.
- Slides with no name will now be displayed in the table of contents as `Untitled Slide`.
These issues only exist in preview mode, so you won't be able to test this using the Storylines demo page. We can verify this is fixed during the next editor testing party.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/449) …

fix styling issues in preview mode

---

StoryRampSchema.json
src/components/panels/map-panel.vue
src/definitions.ts
tailwind.config.js

Not related to any issue, required for CWS migration.
With the way we've implemented Storylines, we don't have any direct way of using custom templates within RAMP. The traditional way of doing this would be to instantiate the map using `const rInstance = createInstance(...)`, and then use rInstance returned from the function to register new Vue templates as such `rInstance.$element.component('new-component', ...)`. 
Since Storylines is instantiating the maps for us, we don't have access to the `rInstance` variable. To solve this, I've added a new `map-created` event which is emitted from the app upon map instantiation that will allow you to register Vue templates on a product host page. 
I've also added a `customTemplates` property to the map panel config so the host page can easily …

emit map-created event on map load

---

package-lock.json
package.json
vite.config.mts

https://github.com/ramp4-pcar4/storylines-editor/issues/380
- [BUILD] excluded `ramp-pcar` from being bundled when building project as plugin for NPM
- published new version `3.2.2` to NPM
- updated `ramp-pcar` to `4.8.0`
None, needs testing after upgrading version in editor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/457)

Exclude ramp-pcar from being bundled in NPM plugin build

---

src/components/panels/slideshow-panel.vue

#412 
- [FIX] slideshow forward and back buttons now match the height of the slideshow
Sometime in between the issue opening and now slideshows became a static height matching the largest item. I did not implement the animation on height changes because as far as I can tell height changes do not happen anymore.
Steps:
1. open sample
2. Scroll down to one of the slideshows
3. hover and see the hover styling and that the button covers the whole height
4. tab to the button and see the same styling and height
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/458)

Make slideshow forward, back buttons full height

---

StoryRampSchema.json
package.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/story/chapter-menu.vue
src/components/story/horizontal-menu.vue
src/components/story/mobile-menu.vue
src/components/story/story-content.vue
src/components/story/story.vue
src/definitions.ts

https://github.com/ramp4-pcar4/storylines-editor/issues/370, https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/9
- [FEATURE] add customization to table of contents menu with each slide having a configurable flag (`includeInToc`) and return to top of page being a global config flag (`returnTop`)
Can revert 0000 config properties before merge if needed. Also will publish new NPM version after all TCEI required fixes are merged. 
Test table of contents navigation/highlighting and ensure all slides with `includeInToc: false` are not included in navigation menu.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/461)

Make ToC slides customizable

---

src/components/story/background-image.vue

https://github.com/ramp4-pcar4/storylines-editor/issues/388
- Fixes an issue where background images would not appear in the editor's preview mode.
This can only be tested through the editor once we put out a new Storylines version. For this PR, just ensure that background transitions are working as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/460)

fix broken background image transitions in editor preview

---

src/components/story/background-image.vue

- Background images are converted to a BLOB after first load and is cached. Should hopefully make background image loading faster.
- I've also increased animation times by 0.1 to hopefully look a tad bit smoother.
Steps:
1. I've temporarily included the TCEI-IECT product in this PR. You can access it by changing the `00000000-0000-0000-0000-000000000000` to `TCEI-IECT` in the demo URL.
2. Ensure images are transitioning smoothly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/463)

improve background image loading

---

index-ca-en.html
index-ca-fr.html

Closes #469
- Updated CDTS to version `5.0.2`.
- Used alternate way to incorporate CDTS to remove the `soyutils.js` file.
- Removed the static CDTS files as they didn't appear to be doing anything.
1. Go to https://ramp4-pcar4.github.io/story-ramp/cdts/index-ca-en.html#/en/00000000-0000-0000-0000-000000000000 and https://ramp4-pcar4.github.io/story-ramp/cdts/index-ca-fr.html#/fr/00000000-0000-0000-0000-000000000000
2. Ensure that everything (including the WET template stuff) is respectful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/470)

Option 1: Use alternate way to incorporate CDTS

---

src/components/story/story.vue

#459
- Added a bottom margin to the storylines content component
- The issue seems to only occur when there is one full screen map slide. Any other full screen slide seem to work fine
Steps:
1. Create a new storylines product (can use storylines editor to do this)
2. Add one full screen map slide
3. Copy the folder for this product over to your local storylines repo
4. Run storylines for this new product
5. Scroll down and observe that the footer isn't cut off anymore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/474)

Fix footer for full screen map

---

public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/story/chapter-menu.vue
src/components/story/horizontal-menu.vue
src/components/story/mobile-menu.vue

Closes #465 
- [FIX] ToC highlighting for customized table of contents menu, will highlight the last slide that exists before current active slide that is part of the ToC menu
Scroll around and make sure there is a highlighted ToC section at all times + highlighted section makes logical sense if it active slide is not part of ToC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/466)

Rework highlighting for flexible table of contents

---

src/components/panels/interactive-map.vue
src/components/story/background-image.vue
src/components/story/slide.vue

#464 
- Added logic to dynamically calculate the observer threshold based on the element and client height instead of just specifying a threshold. This will allow for a more consistent experience on different screen sizes.
- Added checks to see if the slide is switched while a transition is already in progress. If so, the transition will be reset.
- Added a white background to slides that do not have a background image in order to have the transition appear less "jumpy". Let me know if this is an improvement, it can be removed if not.
- Fixed missing alt tag WCAG error by adding `role="presentation"` to the background image.
- Fixed an issue with the interactive map panel not taking up the entire width of the screen when the ToC is horizontal.
If you switch back and forth very quickly …

enhance background transitions

---

src/components/panels/interactive-map.vue
src/components/panels/map-panel.vue
src/components/story/story-content.vue

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/25
- Added a new class to the the `story-content` component that specifies whether the table of contents is oriented horizontally or vertically. This class can be utilized in the sub-components for conditional styling.
- Maps should now adjust height to consider the extra space used by the horizontal table of contents. If the product is using a vertical table of contents the height should still be good.
Steps:
1. Check out the maps in the demo link and ensure their heights match up with the available space on the screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/476)

consider ToC orientation in map height calculation

---

src/components/story/story.vue

#468 
- Makes the pinned title at the top of a product a button that returns you to the top of the page when pressed.
Steps:
2. Scroll down on the page.
3. Click the title and ensure that it returns you to the top of the page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/477)

make pinned title a 'return to top' link

---

src/components/panels/video-panel.vue

Missed part for https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/23
- [FIX] set video panel width to take up all possible space on mobile 
Steps:
1. Test "cumulative effects" video slide on mobile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/479)

Fix video container width at 100% on mobile

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/dynamic-panel.vue
src/definitions.ts

#480 #481
- Added new dynamic panel property `reversed`: if true, the control slide will appear on the right side of the slide and the dynamic content will appear on the left. Defaults to `false.`
- Added new property `hideReturn`: if true, the "Return" button will not appear. Defaults to `false`.
- Added new property `contentWidth`: the width of the text slide will be set to this value if it is defined. This is capped out at the width of the screen in mobile view.
- The return button and dynamic links will now take into consideration the height of the horizontal table of contents when scrolling.
Steps:
2. Play around with the dynamic slide (titled `This slide is dynamic!`) and ensure everything is working as normal.
- - -
This change is [<img …

dynamic panel enhancements

---

src/components/panels/chart-panel.vue
src/components/panels/dynamic-panel.vue
src/components/panels/helpers/fullscreen.vue
src/components/panels/image-panel.vue
src/components/panels/slideshow-panel.vue
src/components/panels/text-panel.vue
src/components/panels/video-panel.vue
src/components/story/horizontal-menu.vue
src/components/story/slide.vue
src/components/story/story-content.vue
src/components/story/story.vue

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/41
https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/42
https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/43
https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/44
https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/45
https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/46
https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/47
- [FIX] remove padding from image containers and add margin between panels (41)
- [FIX] make text panels 95% opacity (42)
- [FIX] align panels margin at top of slide container (43)
- [FIX] removed stacked padding between slides (44)
- [FIX] add border radius to image panels (45)
- [FIX] normalize border radius on panels to be neutral 8px (46) …

Panel styling changes for TCEI UX review

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
public/00000000-0000-0000-0000-000000000000/ramp-config/CommunityDirectory.json
src/components/panels/map-panel.vue
src/definitions.ts

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/8
- [FEATURE] added grid teleport feature to map panel to left of map
- created RAMP config to fill all requirements (keep grid open, symbolize based on "Project Category" field, teleport)
Some methods could be improved upon and may be a bit hacky but mostly just for PoC. Used a merge grid to keep grid open which is probably not the best solution. Also, since there was only sample data in Excel format I could only add this as a CSV file layer and define a custom renderer to replicate expected behavior in issue.
Test first map panel in 0000 test product.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/48 …

PowerBI map for TCEI

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/dynamic-panel.vue
src/components/panels/interactive-map.vue
src/components/panels/map-panel.vue
src/components/panels/panel.vue
src/components/panels/slideshow-panel.vue
src/components/panels/video-panel.vue
src/components/story/chapter-menu.vue
src/components/story/horizontal-menu.vue
src/components/story/slide.vue
src/components/story/story-content.vue

#443, #487
- When resizing the product, everything should now reposition and scale correctly instead of displaying a horizontal scrollbar.
- Also fixes an issue where the horizontal table of contents would cover parts of the stickied content.
- Removed the `top-8` and `top-16` classes from panels as they are no longer required.
Steps:
2. Ensure everything is still positioned correctly, and that the right hand stickied content is nicely aligned at the top of the page under the header.
3. Now, resize the window (not to mobile width just yet).
4. Ensure there is no horizontal scrollbar. Check that everything has resized correctly, and that stickied content is still nicely aligned at the top of the page.
5. Make the page mobile width. Do the same checks and make sure …

fix window resizing issues, horizontal scrollbar overlap

---

index-ca-en.html
index-ca-fr.html
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_fr.json
src/components/story/story.vue
src/definitions.ts

#486 
- Added `breadcrumbs` property to the Storylines config.
- Storylines will now emit a `Storylines-Loaded` event when the config file has finished loading.
- Added an event listener to `index-ca-en.html` and `index-ca-fr.html` that listens for this new event and modifies the breadcrumb list when the config is loaded.
Example breadcrumb entry:
```
breadcrumbs: [
{
"title": "Page Title",
"href": "Link to page"
}
]
```
Steps:
1. Open [index-ca-en.html](https://ramp4-pcar4.github.io/story-ramp/fix-486/index-ca-en.html#/en/00000000-0000-0000-0000-000000000000) / [index-ca-fr.html](https://ramp4-pcar4.github.io/story-ramp/fix-486/index-ca-fr.html#/fr/00000000-0000-0000-0000-000000000000) on the demo page.
2. Ensure that the breadcrumbs are updated when the product finishes loading.
- - - …

add config property to adjust WET breadcrumbs

---

src/components/panels/video-panel.vue

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/63 
- [FIX] video aspect ratio so that is is consistent across all different browser resolutions
Resize the browser and check that the thumbnail of video panels are not cut off.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/494)

Preserve video aspect ratio upon changing browser size

---

package.json
src/components/panels/video-panel.vue

https://github.com/ramp4-pcar4/storylines-editor/issues/408, https://github.com/ramp4-pcar4/storylines-editor/issues/267
- [FEATURE] support for handling captions + transcript files transferred from `configFileStructure`
- [FIX] handle locally uploaded video files by appending `src` directly onto video element
Published `v3.2.7` to NPM https://www.npmjs.com/package/ramp-storylines_demo-scenarios-pcar
Can test in Storylines Editor when package is updated, for now ensure video panels have no errors in demo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/493)

Add support for uploaded video asset files in preview

---

package.json
src/components/story/story.vue
src/definitions.ts

#496 
Should be used with Storylines Editor ToC PR: https://github.com/ramp4-pcar4/storylines-editor/pull/409
- [FEATURE] Allow for undefined slides in Storylines. StoryRAMP will automatically remove these slides before displaying, to prevent crashes.
Steps:
1. Use [these instructions](https://github.com/ramp4-pcar4/story-ramp/discussions/398) to use this new code locally.
2. Open a storylines (using the https://github.com/ramp4-pcar4/storylines-editor/pull/409 branch) with undefined slides (e.g. current version of `00000000-0000-0000-0000-000000000000`)
3. Preview the language with undefined slides (french here)
4. See that the storyline preview doesn't crash, and that the undefined slide doesn't show up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

Handle undefined slides

---

public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/map-panel.vue
src/components/story/mobile-menu.vue

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/15
https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/88
- [FEATURE] make grid teleport customizable through config
- [FIX] adjust teleported grid container styling on mobile resolution
- [FIX] added tooltips for mobile ToC menu items 
Mobile tooltips can look offsetting when clicking on a section to navigate to through ToC, but this may be a Chrome emulator specific issue. 
Steps:
- test Community Directory map with teleported grid functionality + check mobile look
- check ToC tooltips on mobile ToC
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/504)

Adjust grid teleport + mobile changes 

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/helpers/point-of-interest-item.vue
src/components/panels/map-panel.vue
src/components/panels/panel.vue
src/components/panels/slideshow-panel.vue
src/definitions.ts

#503 
- Added the `caption` property to map panels. When provided, the caption will appear under the map as it does for images and slideshows.
- Adjusted the structure of the map panel:
- Instead of hardcoding the map height based on whether there's a horizontal or vertical ToC, and based on whether there's a title or not, the height of the entire panel is now simply based on the ToC orientation.
- Within the panel, the title and caption will take up as much space as required and the map will simply fill in the rest of the available space.
- Point of interest titles now support HTML
- Removed self-start property from slideshow children. Elements should now appear in the center of the slideshow component.
Steps:
2. I've added a new slideshow containing 4 maps with …

add captions to map panels; adjust map layout to better fit titles and captions

---

public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/chart-panel.vue
src/definitions.ts

https://github.com/ramp4-pcar4/storylines-editor/issues/393 
- Added captions for chart panels
Steps:
1. Open the demo page
2. Navigate to the dynamic panel with title `This Slide Is Dynamic!`
3. Open the charts panel
4. Observe the caption under each chart of the slideshow
5. Navigate to the `Highcharts Demo` slide
6. Observe the caption under each chart of the slideshow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/507)

Add caption for chart panels

---

index-ca-en.html
index-ca-fr.html

#509 
- Adds a few lines of code to empty the breadcrumb list when loading a new product.
Steps:
1. Open the demo link.
2. Ensure that breadcrumbs are loading as expected. They should appear as soon as the product loads.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/510)

reset breadcrumbs when loading a new product

---

.gitignore
StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
public/00000000-0000-0000-0000-000000000000/ramp-config/CommunityDirectory.json
public/00000000-0000-0000-0000-000000000000/ramp-config/Locator_Map.json
public/00000000-0000-0000-0000-000000000000/styles/main.css
src/components/panels/helpers/point-of-interest-item.vue
src/components/panels/interactive-map.vue
src/components/story/background-image.vue
src/components/story/story-content.vue
src/definitions.ts

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/86
- [FEAT] added option to add CSS classes to background images
- [FEAT] added config option to specify zoom point details for map panel to perform loop animation
- [FEAT] added option to zoom interactive map out to base extent + a duration config option for zoom animation 
- PoC with slides containing static image + CSS animation, RAMP instance with zoom API call on loop, interactive map with zoom to point of interest
Will need to clean up this PR before merge to remove excess code and demo slides. 
Demo slides for interactive map with zoom animations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/51 …

PoC for map zoomies options

---

index-ca-en.html
index-ca-fr.html
src/app.vue

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/112
- Fixes WCAG errors relating to duplicate `app` and `wb-rsz` classes. I assumed that the error would pop up for `storyramp-app` as well once we fixed `app` so I removed that duplicate as well.
I'm not exactly sure what the difference between `wet.builder.footer({})` and `wet.builder.refFooter({})` is, but removing the latter fixed the issue with `wb-rsz` being added twice and everything still seems to work properly.
Steps:
2. Ensure that these WCAG errors no longer appear.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/517)

remove duplicate class names

---

src/components/panels/slideshow-panel.vue

#508 
- Map components within a slideshow panel will now take up the full screen height (whilst considering title, caption and the bottom slideshow navigation bar). 
This should fix the problem mentioned in the original issue. It is worth noting, however, that this issue may still appear for similar maps that use a Web Mercator basemap.
From the Slack channel:
> Me: Is this expected extent behaviour? It appears that the map gets zoomed out quite a bit when you reduce the map width to ~1175px. It also only appears to happen when using a Web Mercator basemap.
Response from @james-rae:
>prooobably. You give it an extent.  ESRI then has a div of certain size, and that extent, and needs to position the map so the extent fits in the div. You're squeezing in, meaning less room for the width of …

make slideshow map components full height

---

src/components/panels/interactive-map.vue
src/components/panels/video-panel.vue

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/115
- [FIX] add title attribute to iframe element
- [FIX] re-add hilight functionality that was removed by mistake in interactive zoomies PR 
Inspect `iframe` element in devtools for YouTube videos and check hilight feature in interactive map slide.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/521)

Add title to iframe video and restore interactive map hilight

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_fr.json
src/components/panels/helpers/toc-item.vue
src/components/story/chapter-menu.vue
src/components/story/horizontal-menu.vue
src/components/story/mobile-menu.vue
src/components/story/story-content.vue
src/components/story/story.vue
src/definitions.ts
src/lang/lang.csv

Closes #492 
- [FEATURE] adds config option for users to customize Storylines table of contents structure including submenus
For horizontal ToC: https://ramp4-pcar4.github.io/story-ramp/toc-sublists/#/en/00000000-0000-0000-0000-000000000000
For vertical ToC: https://ramp4-pcar4.github.io/story-ramp/toc-sublists/#/fr/00000000-0000-0000-0000-000000000000
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520)

Add support for ToC sublists

---

src/components/story/chapter-menu.vue
src/components/story/horizontal-menu.vue
src/components/story/mobile-menu.vue

#520 
- [FIX] rename sublist dropdown menu to avoid conflict with WET styling
Test the custom table of contents on the Canada.ca template demo pages
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/526)

Rename sublist dropdown class

---

public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/interactive-image-panel.vue

Fixes for #525
- Fixes missing `=` in imageId check which was overwriting every zone to use the first image
- Fixes missing `prose` class causing title not having proper default styles
I didn't want to clutter the config with tests for these small changes so just check that the interactive image panel works as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/527)

Fix interactive-image imageid and title bugs

---

src/components/story/horizontal-menu.vue

#520 
- Add separators for horizontal custom ToC
- Adjust styling (remove top and bottom border, add margin) for sublist dropdown menu
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/528)

Add separator to custom toc + styling adjustments for sublist dropdown

---

src/components/panels/helpers/toc-item.vue

#520 
- [FIX] adjust tooltip positioning for horizontal table of contents parent items to bottom
Test ToC tooltips - parent item labels should be positioned at top of container and sublist item labels should remain on the right.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/529)

Fix tooltip positioning for horizontal custom ToC

---

package.json
src/components/panels/image-panel.vue
src/components/story/background-image.vue
src/components/story/introduction.vue

https://github.com/ramp4-pcar4/storylines-editor/issues/436
- Convert svg images to text rather than blob, so that they are rendered correctly in the storylines editor preview
This would have to be tested through the preview in the storylines editor.
1. Clone this branch locally
2. Follow the step in #398 to make the editor use your local version of storylines
3. Open a product which has an svg logo, an intro slide with an svg background, or a regular slide with an svg background
4. Open the preview for this product
5. Observe that the svg logo and/or background renders correctly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/515)

Fix svg rendering

---

StoryRampSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/helpers/time-slider/time-slider.vue
src/definitions.ts

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/126
- [FEATURE] Adds 'append' mode to timeslider and ability to configure the play mode
- [FEATURE] Interval between timeslider animation steps is configurable
New animation config snippet example:
```json
"animation": {
"playMode": "append",
"interval": 500
}
```
Steps:
1. Scroll down to the map with a timeslider
2. Press play and see only the right handle move (and faster than normal!)
3. See data show up on map but not disappear (until it loops)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/530)

Add timeslider append mode

---

public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_fr.json
src/components/story/chapter-menu.vue
src/components/story/horizontal-menu.vue
src/components/story/mobile-menu.vue

#520 
- [FIX] show last slide highlighting for slides excluded from table of contents
- [FIX] adjust `"tableOfContents"` for test product config to align with updated slides
Removed some slides from configuration, verify when navigating to these slides the table of contents still highlights the last section prior to the slide.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/532)

Fix highlighting for items not included in custom ToC

---

src/components/panels/helpers/scrollama.vue

https://github.com/ramp4-pcar4/storylines-editor/issues/437
- Set top position for the scroll behavior of slides such that the slides corresponding ToC icon is highlighted (rather than the subsequent icon)
Steps:
1. Open a product with a vertical ToC
2. Scroll through the slides, and ensure that the correct ToC icon is highlighted
3. Click on the ToC icons and ensure that they are highlighted (rather than the subsequent icon)
4. Decrease the screen width and repeat steps 2-3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/516)

Fix mismatch with ToC

---

StoryRampSchema.json
src/components/panels/helpers/time-slider/time-slider.vue
src/definitions.ts

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/121
- [FEATURE] Adds two formatter modes to the timeslider, `values` and `ranges`
- `values` uses the slider value as an index for the array of labels
- `ranges` is similar but allows concatenation of ranges in the label above the slider, it also requires a 2d array
`ranges`
`values` 
No formatter
Steps:
1. Go to map with timeslider
2. See fancy labeling
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/533)

Add formatter options to timeslider

---

StoryRampSchema.json
package-lock.json
package.json
src/components/panels/helpers/time-slider/time-slider.vue
src/definitions.ts
src/lang/lang.csv

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/121
- [FEATURE] add `date` formatter option to timeslider
- [FEATURE] add `arcgisDate` option to timeslider to convert slider value to arcgis format for queries
- `date` formatter
- treats the slider values as "epoch time" timestamps and converts that to readable dates. 
- format is specified in config as string an example: "YYYY/M/DD" outputs something like "2025/01/17" 
- Y for year, M for month, D for day, h for hour, m for minute, s for seconds. Number of the letter = length of output (except for month). if YYYY is 2025 then YY would be 25
- arcgis date queries
- arcgis stores date fields with epoch time but is not queryable with them. `arcgisDate` option flags for conversion to arcgis format eg: `TIMESTAMP '2025-01-17 …

Add timeslider support for date fields

---

src/components/story/story-content.vue

#490 
- Fixes an issue where background images would behave strangely if some slides assign the empty string to the backgroundImage property.
This fix worked in the past so it shouldn't need any extensive testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/536)

fix empty background image property behaving incorrectly

---

src/components/panels/map-panel.vue

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/190
- Modified the order of the map component and the teleport container in the map panel. This should ensure that the map is focused before the teleported panel is.
While this now ensures that the map is focused prior to the grid when the grid is teleported to the right of the map, we will now have the same issue pop up if the grid is teleported to the left of the map. 
It doesn't seem like there's a great solution for this. Adding `tabindex` conditionally makes the focus jump all over the place. I could potentially duplicate the `div` with the `grid-teleport`  class and swap the elements depending on whether the grid is teleported to the left or right, but that adds a bunch of unnecessary duplication to the code. 
Steps:
1. …

ensure map is focused before teleported grid

---

src/components/panels/image-panel.vue
src/components/panels/video-panel.vue

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/172
- [FEATURE] apply lazy load for hosted video files
- other changes need to be made directly in Dev
Steps:
1. Check network tab and filter for media
2. Ensure the hosted video file (one in the dynamic slide) is not downloaded until intersected
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/542)

Apply lazy load to hosted videos

---

src/components/panels/interactive-image-panel.vue

https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/187
- Adds the `self-start` class to the image section of the interactive image panel. This will make it scroll down with the page if the text panel exceeds the height of the window.
Steps:
1. Open the demo link.
2. Make the window width just large enough that you don't go into mobile view (just around 650px).
3. Scroll down to the "Interactive image test" slide.
4. Click on the interactive box on the right side of the image and a bunch of Lorem Ipsum text should show up.
5. Scroll up and down to view the text, and ensure the image on the left side is fixed to the top of the screen as you scroll.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

add self-start class to interactive image panel

---

src/components/panels/interactive-map.vue

Closes https://github.com/ramp4-pcar4/tcei-tmx-cwa-storylines/issues/226
- [FIX] missing hilight fixture console error on interactive map zoom
Ensure no console errors on the interactive map panel that complain about undefined when calling `removeHilight` or `addHilight`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/545)

Remove console errors for missing hilight fixture

---

StoryRampSchema.json
package-lock.json
package.json
src/components/panels/panel.vue
src/components/story/story-content.vue
src/definitions.ts

https://github.com/ramp4-pcar4/storylines-editor/issues/491
- Fixed `dist` file names in `package.json`
- Updated version (and pushed to npm registry)
- Added two new interfaces: `SlideshowImagePanel` and `SlideshowChartPanel`. Also added two new panel types: `slideshowImage` and `slideshowChart` 
- These are the same as regular slideshow panels, except that their `items` are restricted to `ImagePanel`'s and `ChartPanel`'s
- Also updated the schema for `multimediaSlideshow`
- The addition of the two new types/interfaces has not yet been published to npm. Once this PR is finalized and merged I can publish a new version
Steps:
1. Create a new panel of type `slideshowImage`
2. Add a few images to the panel (treat it exactly as a regular `slideshow` panel)
3. Load in the product, and observe …

Add new types to schema and definitions, Update version

---

StorylinesSchema.json
public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
src/components/panels/video-panel.vue
src/definitions.ts
src/types.d.ts

https://github.com/ramp4-pcar4/custom-projects/issues/250
- [FEATURE] add config option for enabling video autoplay (non-YT videos)
For any video element with autoplay enabled, I had to disable sound (muted) to avoid accessibility issues. 
Check slides with video autoplay enabled
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/554)

Add support for video autoplay

---

README.md
src/components/panels/interactive-map.vue
src/components/panels/slideshow-panel.vue
src/components/story/chapter-menu.vue
src/components/story/horizontal-menu.vue

#558
- Upon opening/closing a vertical ToC, interactive map panels and slideshow panels will have their width resized accordingly
- Updated README
- ~~After implementing this fix, I noticed that when the vertical ToC is expanded at smaller screen widths (1200px or below), there is some white space to the right of the document, which gets larger as the width is decreased~~
- ~~I had some trouble identifying where this was coming from.~~
- ~~Perhaps some element is overflowing the document? Maybe the window has a min width set somewhere?~~
- ~~I can open a new issue and look deeper into this once this PR is merged~~
Steps:
1. Open 000... product
2. Scroll down to slides
3. Expand vertical ToC
4. Notice there is no horizontal scrollbar
5. Click a ToC item, and notice that the corresponding …

Resize interactive map and slideshow panels upon expanding ToC, Update README

---

src/components/panels/helpers/toc-item.vue
src/components/panels/image-panel.vue
src/components/panels/interactive-image-panel.vue
src/components/panels/panel.vue
src/components/panels/video-panel.vue
src/components/story/chapter-menu.vue
src/components/story/horizontal-menu.vue
src/components/story/mobile-menu.vue
src/components/story/slide.vue
src/components/story/story-content.vue
src/components/story/story.vue
src/event-bus.ts
src/router/index.ts

#553
- When lazy loading is enabled, slides will be force loaded whenever they are navigated past during a route navigation resulting from clicking a ToC item
- Created a 100ms delay for routing, so that the images/videos have enough time to force load in before they are navigated past
- Added some comments to help out with tested. Should be removed prior to merging
Steps:
1. Load in a large product with images and video
2. Ensure lazy loading is enabled
3. Click on the ToC item corresponding to a slide towards the end
4. Ensure that the slide is navigated to correctly, and that the ToC item you clicked has a blue highlight
5. Ensure this works for horizontal, vertical and mobile ToC's
6. Ensure there are no issues when lazy loading in disabled
- - -
This change is [<img …

Force load slides when navigating past them with lazy loading

---

src/components/panels/text-panel.vue
src/components/story/chapter-menu.vue

https://github.com/ramp4-pcar4/custom-projects/issues/280
- Removes an empty `div` at the end of the table of contents that was causing an accessibility error.
- Only displays the header tag in a text panel if a title is provided.
Steps:
1. Open the demo link.
2. Ensure that the table of contents is still working as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/storylines/569)

remove empty div from ToC

---

package.json
src/components/panels/helpers/text-content.vue
src/components/panels/text-panel.vue

https://github.com/ramp4-pcar4/storylines-editor/issues/619
- Imports AudioPlayer and TextContent as async components. Everything should still work the same for Storylines, but hopefully this fixes the issue with text not rendering within RESPECT.
- Bump Storylines version to 3.4.1.
Steps:
1. Open demo link.
2. Ensure text and audio player is still working as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/storylines/570)

import AudioPlayer and TextContent as async components

---

.github/slack-bot.py
package-lock.json

The bot gave links from outside before. This could be a security risk. Only organization github links (github.com/ramp4-pcar4) are now permitted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/storylines/584)

Slackbot: Improve link handling (block all exterior links)

---

src/components/panels/helpers/scrollama.vue
src/components/story/background-image.vue
src/components/story/story.vue

Issue #592 
- Using more accurate actual measurements of the page to determine footerpadding height
- When there is only one slide and it is very small, seems that the footerpadding is just a tad too large, not sure what is causing this but I suspect something about the loading order of elements on the page
- When you load or reload the page on any zoom size, it works as intended, but if you zoom in while you're on the page sometimes the last chapter ToC button does not highlight correctly — not sure if I should just add some extra footerpadding space for this or if it is fine
- I will revert the 00000000-0000-0000-0000-000000000000_en product file when this PR is approved
Steps:
1. Use different slide heights as the last slide 
2. See footer change height based on last slide
- - -
This …

Preview footer now should be perfect height

---

package.json
src/components/panels/video-panel.vue

https://github.com/ramp4-pcar4/storylines-editor/issues/719, https://github.com/ramp4-pcar4/storylines-editor/pull/711
- fixes issue of RESPECT preview breaking for saved products with a YT video panel (e.g. 0000 product) resulting in no existing video ref
- published version 3.5.7 to NPM
Test loading 0000 product in demo page in https://github.com/ramp4-pcar4/storylines-editor/pull/711, however is local issue so will need to confirm after merge
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramp4-pcar4/storylines/598)

Fix RESPECT local preview build issue for missing video ref
